In [1]:
import pandas as pd

In [9]:
data_pendidikan = pd.read_csv('data/data_fix/data_pendidikan.csv', index_col='Provinsi')
data_pendidikan.head()

,SD_2019,SD_2020,SD_2021,SMP_2019,SMP_2020,SMP_2021,SMA_2019,SMA_2020,SMA_2021
Provinsi,,,,,,,,,
ACEH,98.6,98.3,99.4,89.5,90.9,93.4,70.0,70.1,74.4
BALI,98.3,96.7,97.0,93.3,93.2,94.3,64.5,74.9,75.9
BANTEN,96.3,96.0,98.8,87.4,86.7,90.6,56.9,64.2,66.9
BENGKULU,93.3,95.2,98.2,85.1,87.7,89.9,61.5,62.7,62.5
DI YOGYAKARTA,94.9,96.4,98.5,92.3,92.4,94.9,84.5,88.0,90.1

In [ ]:
data_pendidikan_sd